### PR TITLE
Immutable vnodes

### PR DESCRIPTION
**Pull request by buntec**
Experiments in making vnodes immutable.

### CODE REVIEW

**Comment by buntec** [comment]
This is currently broken despite all tests passing. Yikes!

**Comment by buntec** [comment]
Looks better now, though the fact that the tests didn't catch these issues is disconcerting!

**Comment by buntec** [comment]
Tests are passing and some ff4s examples look ok, too. The biggest concern is probably performance, although the todo-mvc benchmark using ff4s barely budged after the change. Not sure what to make of that.

**Comment by armanbilge** [comment]
> though the fact that the tests didn't catch these issues is disconcerting!

This would be my concern, would be nice to add some tests for these.

Unfortunately I don't think I can do an in-depth review of this one, but if it works it works :) 👍

**Comment by buntec** [comment]
> > though the fact that the tests didn't catch these issues is disconcerting!
> 
> This would be my concern, would be nice to add some tests for these.
> 
> Unfortunately I don't think I can do an in-depth review of this one, but if it works it works :) 👍

No worries! I'm aware that this is a big change, and one that marks a clear departure from the original snabbdom. Any high level feedback would still be appreciated ;). Having immutable vnodes is one of the things mentioned by @cornerman in this [issue](https://github.com/buntec/scala-js-snabbdom/issues/14#issuecomment-1120278952).

I'll try to increase test coverage to include the cases I came across when making these changes.

**Pull request merged**
